### ISSUE TITLE
Cannot redirect a user to the authoriation URL, blocked by CORS error.

### ISSUE THREAD

**Issue by Obliquey** [PrimeAcademy/citrine-syllabus#1]
## Description

* What do you want your code to do?
* - Redirect to the URL that Spotify send back to me when I've made an authorization request, where the user can authorize my app.
* What is your code actually doing?
* - Blocking the request from processing, arguably due to CORS policy.

---

## Screenshots / Code Snippets

* Include a screenshot of the problem, and/or copy-paste relevant code and error messages.
*  Here is the error I'm receiving. The URL within the error is the one I want to redirect to; if I click on it, it brings me to Spotify's user authorization page.
<img width="552" alt="image" src="https://github.com/PrimeAcademy/citrine-syllabus/assets/108906250/740556b1-0a91-4abb-b2cf-5e0ffd213114">

* Here is my request code. We get to the .then() portion of the request, but something is up with the res.redirect. 
* 
![image](https://github.com/PrimeAcademy/citrine-syllabus/assets/108906250/b7f9977d-1d63-40ef-b93a-9283b30ffbd8)

* Note that you can drag-and-drop images into the github editor!

---

## What did you try? Who did you ask?
I've tried adding CORS policy headers, following along with both the Spotify documentation and other online tutorials. All of them end in this CORS error.
* Briefly describe your debug process. What did you do to isolate the issue?
*I've moved the requests from a router to the main server file (specifically to try to implement cors() for my express app in the same file location as the request).
I've tried copy and pasting Spotify's documentation, transferring another person's implementation into my own, etc. Everything is pointing to my browser (or Spotify) not allowing me to redirect to this URL.
    * Remember to "bubble up" your questions. Start with Google, then your pod, and then your cohort.  

---

## When was the last time you took a break?
Since lunch, but I was working on this before then too.
* Like, a real break. Bugs have this amazing way of just disappearing into nothingness when you take some time to clear your head. Go for a walk or something!

**Comment by YuhBoh** [comment]
What do you want your code to do?
    upload youtube links into database
    
What is your code actually doing?
    returning an invalid hook call error

![image](https://github.com/PrimeAcademy/citrine-syllabus/assets/116762385/1ee9a0d8-3b03-4252-b6a4-51efb14b1443)

   
<img width="525" alt="Screenshot 2023-05-23 at 1 03 29 PM" src="https://github.com/PrimeAcademy/citrine-syllabus/assets/116762385/4e809c28-6b30-44c3-aa1d-7dee0c6ed7b9">

What did you try? Who did you ask?
I tried to follow the code that the warning gave; isolated problem to saga file (i think?); Asked cohort member to double check.

When was the last time you took a break?
Career Development

**Comment by aharasymiw** [comment]
Switching the initial call to the server from a button with a click handler, to an <a> tag with a universal uri (https://localhost:5000/api/spotify/login) did the trick.
