### ISSUE TITLE
Final Review of My base Mode

### ISSUE THREAD

**Issue by z-ilyas** [PrimeAcademy/citrine-syllabus#10]
## Description

* What do you want your code to do?
- My code works fine but just wanted a second pair of eyes to look at my project. Today at 4.3o pm works for me.
- Andrew asked me to make an issue.  
* What is your code actually doing?

---

## Screenshots / Code Snippets

* Include a screenshot of the problem, and/or copy-paste relevant code and error messages.
* Note that you can drag-and-drop images into the github editor!

---

## What did you try? Who did you ask?

* Briefly describe your debug process. What did you do to isolate the issue?
    * Remember to "bubble up" your questions. Start with Google, then your pod, and then your cohort.  

---

## When was the last time you took a break?

* Like, a real break. Bugs have this amazing way of just disappearing into nothingness when you take some time to clear your head. Go for a walk or something!

**Comment by z-ilyas** [comment]
My code works fine but just wanted a second pair of eyes to look at my project. Today at 4.30 pm works for me.
Andrew asked me to make an issue.

**Comment by aharasymiw** [comment]
Calendar invite sent to meet
