### ISSUE TITLE
Insert time into database

### ISSUE THREAD

**Issue by ilhan-dahir** [PrimeAcademy/citrine-syllabus#11]
## Description

* What do you want your code to do?
 I want to insert a time into my table.
* What is your code actually doing?
I can insert a Time when Im running from postgres, but when I make the call from my server, I get invalid input type.
---

## Screenshots / Code Snippets

* Include a screenshot of the problem, and/or copy-paste relevant code and error messages.
* Note that you can drag-and-drop images into the github editor
*
SqlValues>>>> [ 'asdf', 'adfa', 'asdf', 'adf', '14:02', '01:02' ]
/newRide failed  error: invalid input syntax for type time: "$5"

`
const sqlText = `
    WITH inserted_client AS (
        INSERT INTO "clients" ("client_name", "default_location")
              VALUES ('$1', '$2') RETURNING id
              )
        INSERT INTO rides
           ("pickup_location",
            "dropoff_location", 
            "pickup_time",
            "dropoff_time",
            "client_id")
           VALUES
        ('$3', 
        '$4', 
        '$5', 
        '$6', 
        (SELECT inserted_client.id FROM inserted_client));
    `
`

---

## What did you try? Who did you ask?

I googled and console logged my query to see if it looked right going into my table. it did look right and am able to run the query in postico.

## When was the last time you took a break? 

* Like, a real break. Bugs have this amazing way of just disappearing into nothingness when you take some time to clear your head. Go for a walk or something!

**Comment by aharasymiw** [comment]
Invite Sent
