### ISSUE TITLE
Invalid Hook call

### ISSUE THREAD

**Issue by YuhBoh** [PrimeAcademy/citrine-syllabus#2]
What do you want your code to do?
upload youtube links into database

What is your code actually doing?
returning an invalid hook call error

![image](https://github.com/PrimeAcademy/citrine-syllabus/assets/116762385/bc2b3229-c392-447d-b5d0-7f88b63d5e67)

<img width="477" alt="Screenshot 2023-05-23 at 1 33 27 PM" src="https://github.com/PrimeAcademy/citrine-syllabus/assets/116762385/cc3b8cad-a797-4ee6-af21-5d5d982a1ede">

What did you try? Who did you ask?
I tried to follow the code that the warning gave; isolated problem to saga file (i think?); Asked cohort member to double check.

When was the last time you took a break?
Career Development

**Comment by matthew-black** [comment]
Heyo! Check out the `createElement` Saga function here:
* https://github.com/PrimeAcademy/citrine-sagas/blob/main/src/index.js

We only use `useDispatch` inside React components. If you want to send an action to the redux store *from a Saga function*, you must use `put`.

**Comment by aharasymiw** [comment]
Closing since progress was made.  Feel free to reach out again.
