### ISSUE TITLE
CSS problem

### ISSUE THREAD

**Issue by YuhBoh** [PrimeAcademy/citrine-syllabus#4]
## Description

* What do you want your code to do?
   Create a pop-up menu that covers background in semi transparent color so it's not interactable until pop-up menu is closed.
* What is your code actually doing?
  Creates a pop-up menu with background, but the container is lined up with each <li> so the background gets lower.

---

## Screenshots / Code Snippets
![image](https://github.com/PrimeAcademy/citrine-syllabus/assets/116762385/3d0b45e3-ec96-4c02-ba8e-be0d010f31c9)
![image](https://github.com/PrimeAcademy/citrine-syllabus/assets/116762385/d3276529-771e-4849-8d3f-93f3f1849946)
<img width="540" alt="Screenshot 2023-05-25 at 8 53 09 AM" src="https://github.com/PrimeAcademy/citrine-syllabus/assets/116762385/9bf52804-69d3-4dde-ba52-afdaae29a33f">
---

## What did you try? Who did you ask?
Asked some cohorts about CSS; Looked up some css videos; Followed a tutorial; Experimented with some CSS.

---

## When was the last time you took a break?

8AM PST

**Comment by aharasymiw** [comment]
A clever workaround is totally acceptable :)
