### ISSUE TITLE
CSS overlay problem?

### ISSUE THREAD

**Issue by YuhBoh** [PrimeAcademy/citrine-syllabus#6]
## Description

I want my overlay to cover the entire screen and have a pop-up menu show up relative to where I'm clicking it.

The overlay covers up a portion of the screen and it's position is relative to where I click it. Also the pop-up menu shows up behind images.

---

## Screenshots / Code Snippets

* Include a screenshot of the problem, and/or copy-paste relevant code and error messages.
![image](https://github.com/PrimeAcademy/citrine-syllabus/assets/116762385/d723d8dd-7c03-44e8-9f7b-a26eb9e1a9e3)

<img width="687" alt="image" src="https://github.com/PrimeAcademy/citrine-syllabus/assets/116762385/d5002697-6227-4787-b9e8-41229617f091">
<img width="694" alt="image" src="https://github.com/PrimeAcademy/citrine-syllabus/assets/116762385/e8e52a99-5428-47ca-af64-8104cea6fdc0">
<img width="690" alt="image" src="https://github.com/PrimeAcademy/citrine-syllabus/assets/116762385/58ca5880-7e22-4183-ae0e-a0b588e422b0">

---

## What did you try? Who did you ask?

* Briefly describe your debug process. What did you do to isolate the issue?
    * Remember to "bubble up" your questions. Start with Google, then your pod, and then your cohort.  
Tried looking through css tutorials for js react. Tried fixing it on my own. Contacting cohorts for help.
---

## When was the last time you took a break?

11 PM PST Monday

**Comment by matthew-black** [comment]
It looks like the part you're calling the overlay needs some CSS added to it that will:
* Force it to cover 100% of the browser window's height and width.

Right now, it appears to be taking up 100% of the space *available to it*. Which is to say that it doesn't cover the left navbar or top header.

---

To make the pop-up appear "on top of" everything else, you'll need to apply a `z-index` CSS property to tell the browser to render it on top:
* https://css-tricks.com/almanac/properties/z/z-index/

**Comment by aharasymiw** [comment]
Matt beat me to this, with fantastic advice.  After you look into these ideas, let me know if you are stuck and need to meet.
