### ISSUE TITLE
Feedback plz

### ISSUE THREAD

**Issue by MrOrtiz1988** [PrimeAcademy/citrine-syllabus#7]
I would like to present my project to matt or andrew just to get some feedback or thoughts :)

**Comment by aharasymiw** [comment]
Let's chat after stand-up tomorrow.

**Comment by MrOrtiz1988** [comment]
Gotchu! Sent from Mail for Windows From: Andrew HarasymiwSent: Tuesday, May 30, 2023 6:32 PMTo: PrimeAcademy/citrine-syllabusCc: Luis Ortiz; AuthorSubject: Re: [PrimeAcademy/citrine-syllabus] Feedback plz (Issue #7) Let's chat after stand-up tomorrow.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
